kind: Service
apiVersion: v1
metadata:
  name: bitbucket
  labels:
    app: bitbucket
spec:
  selector:
    app: bitbucket
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7990
  - name: git
    protocol: TCP
    port: 7999
    targetPort: 7999
  type: LoadBalancer
